version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pg_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: crypto_bot
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

    command: >
      bash -c "
        alembic upgrade head &&
        python main.py
      "
    volumes:
      - ./storage:/app/storage

volumes:
  pg_data:
